services:
  mathdb:
    image: postgres:16.2-alpine3.19
    container_name: mathdb
    environment:
      - POSTGRES_DB=math
      - POSTGRES_USER=mathAdmin
      - POSTGRES_PASSWORD=1234567890
    volumes:
      - mathdb_data:/var/lib/postgresql/data
    ports:
      - 8100:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d math" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
  historydb:
    image: postgres:16.2-alpine3.19
    container_name: historydb
    environment:
      - POSTGRES_DB=history
      - POSTGRES_USER=historyAdmin
      - POSTGRES_PASSWORD=1234567890
    volumes:
      - historydb_data:/var/lib/postgresql/data
    ports:
      - 8101:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d history" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mathdb_data:
    name: mathdata
  historydb_data:
    name: historydata