spring:
  application:
    name: math
  datasource:
    driver-class-name: org.postgresql.Driver
    username: mathAdmin
    password: 1234567890
    url: jdbc:postgresql://localhost:8100/math
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    kafka-topic:
      producer: "logs"
    bootstrap-servers: localhost:29092
server:
  port: 8081