spring:
  application:
    name: history
  datasource:
    url: jdbc:postgresql://localhost:8101/history
    username: historyAdmin
    password: 1234567890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082